
export const events = [{
    ID_EVENT: 111, 
    USER_NAME: 'nrrojasfe', 
    NAME_LOC_SPORT: 'LA PLAYITA',
    NAME_SPORT: 'YOGA',
    EVENT_DESCRIPTION: "Este es un evento de esparcimiento y en el que se van a hacer diversos ejercicios de relajacion para ttener un equilibrio de cuerpo y mente",
    EVENT_INIT: '12 de enero',
    EVENT_END: '12 de enero',
    CAPACITY: 20,
    EVENT_INIT_HOUR: '12:00',
    EVENT_FINISH_HOUR: '15:00',
},
{
    ID_EVENT: 112, 
    USER_NAME: 'nrrojasfe', 
    NAME_LOC_SPORT: 'CONCHA ACUSTICA',
    NAME_SPORT: 'VOLLEY',
    EVENT_DESCRIPTION: "Este es un evento de esparcimiento y en el que se van a hacer diversos ejercicios de relajacion para ttener un equilibrio de cuerpo y mente",
    EVENT_INIT: '12 de enero',
    EVENT_END: '12 de enero',
    CAPACITY: 20,
    EVENT_INIT_HOUR: '12:00',
    EVENT_FINISH_HOUR: '15:00',
},
{
    ID_EVENT: 113, 
    USER_NAME: 'nrrojasfe', 
    NAME_LOC_SPORT: 'ESTADIO',
    NAME_SPORT: 'FUTBOL',
    EVENT_DESCRIPTION: "Este es un evento de esparcimiento y en el que se van a hacer diversos ejercicios de relajacion para ttener un equilibrio de cuerpo y mente",
    EVENT_INIT: '12 de enero',
    EVENT_END: '12 de enero',
    CAPACITY: 20,
    EVENT_INIT_HOUR: '12:00',
    EVENT_FINISH_HOUR: '15:00',
}]

